### ISSUE TITLE
Ancestor files no longer available?

### ISSUE THREAD

**Issue by jon4thin** [konradjk/loftee#100]
I found that the 2 links for the ancestor files:
http://www.broadinstitute.org/~konradk/loftee/human_ancestor.fa.rz 
http://www.broadinstitute.org/~konradk/loftee/human_ancestor.fa.rz.fai

are both dead:
Not Found
The requested URL was not found on this server.

**Comment by konradjk** [comment]
Hello!

These moved a while back, apologies if there's still a dead link somewhere. They are now in build-specific directories: e.g. https://personal.broadinstitute.org/konradk/loftee_data/GRCh37/
