### ISSUE TITLE
WARNING: Failed to compile plugin LoF: Can't locate Bio/DB/BigWig.pm in @INC (you may need to install the Bio::DB::BigWig module)

### ISSUE THREAD

**Issue by ethankreuzer** [konradjk/loftee#107]
Hello,

I am trying to run loftee with vep and am experiencing the above error. I cloned loftee from the grch38 branch and not the master. Here is my command 

vep -i chr22_set_ID.vcf \
        --plugin LoF,loftee_path:/ethan.kreuzer/.vep/Plugins/loftee \
        --dir_plugins /ethan.kreuzer/.vep/Plugins/loftee \
        -everything \
        --assembly GRCh38 \
        --offline \
        --dir_cache /home/richards/ethan.kreuzer/.vep \
        --cache -o finalAnnot.chr22.txt ;

I get the following error :

WARNING: Failed to compile plugin LoF: Can't locate Bio/DB/BigWig.pm in @INC (you may need to install the Bio::DB::BigWig module) 

Not sure what needs to be done. Thank you

**Comment by ngbarlow-gnq** [comment]
I am having the same issue, how did you end up resolving this warning?
