### ISSUE TITLE
post-process VEP decorated VCF with LOFTEE

### ISSUE THREAD

**Issue by indapa** [konradjk/loftee#13]
Is it possible to post process a VEP generated VCF with LOFTEE? Or does is the only way to run it is with the --plugin option? I have a large number of VCFs with VEP annotations, but weren't run with LOFTEE.

**Comment by bryketos** [comment]
Have you tried using the --keep_csq option in VEP?
http://useast.ensembl.org/info/docs/tools/vep/script/true
-Brian Cole

**Comment by indapa** [comment]
I didn't know about that option, yes that should work! Thanks, Brian!
