### ISSUE TITLE
compilation failed

### ISSUE THREAD

**Issue by saralpulit** [konradjk/loftee#14]
Hello,

I'm worried that I'm bugging you with a simple error but I just can't figure it out what's going on. I am attempting to run the LOFTEE plugin with VEP, and I continue to get an error when I try and run it (please see screenshots). I am using perl > 5.10, have all the supporting files in place, etc. but continue to see:

Bareword found where operator expected at /hpc/local/CentOS7/hers_en/software/ensembl-tools-release-85/scripts/variant_effect_predictor/Plugins/splice_module.pl line 6, near ""en" class"
       	(Missing operator before class?)
Bareword found where operator expected at /hpc/local/CentOS7/hers_en/software/ensembl-tools-release-85/scripts/variant_effect_predictor/Plugins/splice_module.pl line 26, near "<title>loftee"
       	(Missing operator before loftee?)
2016-09-26 22:45:06 - Failed to compile plugin LoF: Unrecognized character \xC2; marked by <-- HERE after at master <-- HERE near column 46 at /hpc/local/CentOS7/hers_en/software/ensembl-tools-release-85/scripts/variant_effect_predictor/Plugins/splice_module.pl line 26.
Compilation failed in require at /hpc/local/CentOS7/hers_en/software/ensembl-tools-release-85/scripts/variant_effect_predictor/Plugins/LoF.pm line 24.
Compilation failed in require at (eval 142) line 2.
BEGIN failed--compilation aborted at (eval 142) line 2.

**Comment by bryketos** [comment]
Hello,

Can you please verify that you can compile the splice_module.pl file with your Perl?  See this example I just did with a fresh git clone from this repository (shell prompt elided):

$ perl -c splice_module.pl 
splice_module.pl syntax OK

If this generates an error you might try to reclone the repository or update your own repo with a fresh pull.  Make sure the cloned or pulled perl sources end up in your VEP plugins directory.

Thanks,
Brian S. Cole, PhD
Penn Institute for Biomedical Informatics

**Comment by konradjk** [comment]
Hmm, yes, that does seem a bit odd. Did you clone LOFTEE directly from this repo? I'm wondering if maybe a download went wrong at some point? If something's wrong after re-cloning, maybe try a direct download of the file: https://raw.githubusercontent.com/konradjk/loftee/master/splice_module.pl
Let me know if it still fails at that point

**Comment by saralpulit** [comment]
So bizarre! Yes, something must have happened when I cloned the repository. I re-downloaded splice_module.pl and it compiles and runs fine. Sorry for bothering with something so simple. And thanks for the quick responses!
