### ISSUE TITLE
using loftee and GRCh38

### ISSUE THREAD

**Issue by matthdsm** [konradjk/loftee#15]
Hi, 

Is it possible to use loftee with GRCh38? Where should I source the human ancestor file from? Or can I just use the same?

Thanks
M

**Comment by matthdsm** [comment]
Hi,

I'd like to follow up on this question, is there a liftovered version of the human ancestor file available? Or can we just use the same fasta file?

Thanks
M

**Comment by snashraf** [comment]
Hi can you please share whatever command you have been using for Loftee annotation ? I am using below command and not getting even one LOF Mutation in my VCF files.

perl /gpfs/software/genomics/VEP/ensembl-tools-release-83/scripts/variant_effect_predictor/variant_effect_predictor.pl -i PMC01_jointCalling.filtered.snps.indels.vcf --cache --assembly GRCh37 --offline --dir_cache /gpfs/projects/vep/ --vcf --everything --sift --polyphen --hgvs --fasta /gpfs/projects/refData/Homo_sapiens.GRCh37.dna.primary_assembly.fa --force --symbol --dir_plugins /gpfs/software/genomics/VEP/loftee  -o PMC01_jointCalling.filtered.snps.indels_VEP.vcf
perl /gpfs/software/genomics/VEP/ensembl-tools-release-83/scripts/variant_effect_predictor/variant_effect_predictor.pl -i PMC01_jointCalling.filtered.snps.indels.vcf --cache --assembly GRCh37 --offline --dir_cache /gpfs/projects/vep/ --vcf --everything --sift --polyphen --hgvs --fasta /gpfs/projects/refData/Homo_sapiens.GRCh37.dna.primary_assembly.fa --force --symbol --dir_plugins /gpfs/software/genomics/VEP/loftee ----plugin LoF -o PMC01_jointCalling.filtered.snps.indels_VEP.vcf

**Comment by rvernica** [comment]
@matthdsm did you find a resolution to this issue?

**Comment by matthdsm** [comment]
Hi @rvernica 

Not exactly, I've just started using the reference genome.
Cheers
M
