### ISSUE TITLE
where to download phylocsf.sql?

### ISSUE THREAD

**Issue by luoyufei** [konradjk/loftee#16]
Hi, 
I wanted to apply LOFTEE to filter variants. 
But the link of phylocsf.sql didn't work anymore ...
Please tell me where can I download it?
Thank you!

**Comment by ttriche** [comment]
he seems to be right,
https://www.broadinstitute.org/~konradk/loftee/phylocsf.sql.gz and
https://www.broadinstitute.org/~konradk/loftee/phylocsf.sql seem no longer
to exist


--t

**Comment by luoyufei** [comment]
Oh thanks for having repaired the link, it works now!
