### ISSUE TITLE
Use of uninitialized value in split at LoF.pm

### ISSUE THREAD

**Issue by youngchan919** [konradjk/loftee#18]
When running vep with Loftee, it issues a info: `Use of uninitialized value in split at .../LoF.pm`.

**Comment by konradjk** [comment]
I've seen this sporadically before, but if it's only a few times per genome, it's generally not a cause for alarm. If you can find a single variant that triggers this warning, I'd be happy to take a look. Closing for now, but feel free to re-open the issue if it's still occuring.
