### ISSUE TITLE
WARNING: Plugin 'LoF' went wrong: Illegal division by zero at

### ISSUE THREAD

**Issue by yunusbb** [konradjk/loftee#25]
Hello,

When I am running LoF plugin through VEP (as shown below), I am getting warnings and no LoF annotation in the output. I have tried to google and read the online documentation but could not find the solution. Can anyone help me with this? 

./ensembl-vep/vep -i /ebc_data/bayazit1/PRE_MIGRATION_ADMIX/dsets/full_seq/vcf_from_Vasily/NE_chr_2.rsnum.vcf.gz \
--cache --force_overwrite --dir_cache /ebc_data/bayazit1/.vep --offline --sift b --symbol \
--canonical -polyphen p \
-plugin LoF,loftee_path:/ebc_data/bayazit1/.vep/Plugins/loftee,human_ancestor_fa:/ebc_data/bayazit1/PRE_MIGRATION_ADMIX/dsets/full_seq/vcf_from_Vasily/ensembl-vep/ANC_SEQ/human_ancestor.fa.gz,\
conservation_file:/ebc_data/bayazit1/PRE_MIGRATION_ADMIX/dsets/full_seq/vcf_from_Vasily/ensembl-vep/PhyloCSF_SQL_database/phylocsf.sql.gz \
--dir_plugins /ebc_data/bayazit1/.vep/Plugins/loftee \
-o /gpfs/hpchome/bayazit1/udustorage/VEP_LoF/LoF_RS_added_VEP_output_for_dset_NE_chr_2.txt

WARNING: Plugin 'LoF' went wrong: Illegal division by zero at /ebc_data/bayazit1/.vep/Plugins/loftee/maxEntScan/score3.pl line 157, <$fh> line 5014.
WARNING: Plugin 'LoF' went wrong: Illegal division by zero at /ebc_data/bayazit1/.vep/Plugins/loftee/maxEntScan/score5.pl line 93, <$fh> line 5014.
WARNING: Plugin 'LoF' went wrong: Can't call method "execute" on an undefined value at /ebc_data/bayazit1/.vep/Plugins/loftee/LoF.pm line 509, <$fh> line 5014.
WARNING: Plugin 'LoF' went wrong: Illegal division by zero at /ebc_data/bayazit1/.vep/Plugins/loftee/maxEntScan/score3.pl line 157, <$fh> line 10014.
WARNING: Plugin 'LoF' went wrong: Illegal division by zero at /ebc_data/bayazit1/.vep/Plugins/loftee/maxEntScan/score5.pl line 93, <$fh> line 10014.
WARNING: Plugin 'LoF' went wrong: Illegal division by zero at /ebc_data/bayazit1/.vep/Plugins/loftee/maxEntScan/score5.pl line 93, <$fh> line 15014.
WARNING: Plugin 'LoF' went wrong: Can't call method "execute" on an undefined value at /ebc_data/bayazit1/.vep/Plugins/loftee/LoF.pm line 509, <$fh> line 15014.
W
... more lines

**Comment by elliekinz** [comment]
@yunusbb Did you find out what the problem was?
I'm having the same issue.

**Comment by yunusbb** [comment]
Hi elliekinz,
No, I could not find the solution.

**Comment by birndle** [comment]
Hello yunusbb and elliekinz,

Sorry about this. I'm not sure what the problem is because I can't replicate this error. Can you send me your input files for testing?

Thank you, 
Dan

**Comment by yunusbb** [comment]
Hello Daniel,
Thank you for your response. Here is my input VCF file. Sorry, it is quite
big ;)​
 NE_chr_2.rsnum.vcf.gz
<https://drive.google.com/file/d/1OK-KJj6UcxBAgz0k-7tzoMZVNmmtgNOU/view?usp=drive_web>
​​
 NE_chr_2.rsnum.vcf.gz.tbi
<https://drive.google.com/file/d/104IdpxyIja9KzO6EN009e3fHXLdbCIN0/view?usp=drive_web>
​

**Comment by birndle** [comment]
Hey again -

Just wanted to recap. I was able to reproduce your error, but I've found that it only occurs for me when using the latest --cache_version 91. We are talking to the folks at VEP about why the cache is not behaving as expected. But for now, using --cache_version 89 should fix your problems. Please let me know if it does not.

Best, 
Dan

**Comment by yunusbb** [comment]
Hello,

I have tested with cache version 89 by adding '--cache_version 89' and
warning messages are still there ;(

# here are my commands:

# 1: downloading cache 89 version files:

cd $HOME/.vep

curl -O
ftp://ftp.ensembl.org/pub/release-89/variation/VEP/homo_sapiens_vep_89_GRCh37.tar.gz

tar xzf homo_sapiens_vep_89_GRCh37.tar.gz

# 2: running vep:

./ensembl-vep/vep -i ${w_dir}/NE_chr_22.vcf.gz \
--cache --cache_version 89 --vcf --force_overwrite --dir_cache
/ebc_data/bayazit1/.vep --offline --sift b --symbol \
-plugin
LoF,loftee_path:/ebc_data/bayazit1/.vep/Plugins/loftee,human_ancestor_fa:${w_dir}/ensembl-vep/ANC_SEQ/human_ancestor.fa.gz,\
conservation_file:${w_dir}/ensembl-vep/PhyloCSF_SQL_database/phylocsf.sql.gz
\
--dir_plugins /ebc_data/bayazit1/.vep/Plugins/loftee \
 -o ${w_dir}/VEP_OUT/LoF_cache_v89_VEP_output_for_dset_NE_chr_22.vcf

# 3: warnings:

head LoF_cache_v89_VEP_output_for_dset_NE_chr_22.vcf_warnings.txt
WARNING: Plugin 'LoF' went wrong: Can't call method "execute" on an
undefined value at /ebc_data/bayazit1/.vep/Plugins/loftee/LoF.pm line 509,
<$fh> line 5010.
WARNING: Plugin 'LoF' went wrong: Illegal division by zero at
/ebc_data/bayazit1/.vep/Plugins/loftee/maxEntScan/score5.pl line 93, <$fh>
line 5010.
WARNING: Plugin 'LoF' went wrong: Illegal division by zero at
/ebc_data/bayazit1/.vep/Plugins/loftee/maxEntScan/score3.pl line 157, <$fh>
line 5010.
WARNING: Plugin 'LoF' went wrong: Illegal division by zero at
/ebc_data/bayazit1/.vep/Plugins/loftee/maxEntScan/score5.pl line 93, <$fh>
line 10010.
...

**Comment by birndle** [comment]
Hi,

Thanks for the detailed response. Are you getting any annotations from LOFTEE? For example if you `grep` your output file for the string "DONOR_DISRUPTING" do you get any output?

Dan

**Comment by yunusbb** [comment]
Hi,

Sorry for the delayed response.

lookup for 'DONOR_DISRUPTING' in the two largest chromosomes:

-bash-4.2$ cat LoF_cache_v89_VEP_output_for_dset_NE_chr_2.vcf | grep
DONOR_DISRUPTING
-bash-4.2$ cat LoF_cache_v89_VEP_output_for_dset_NE_chr_1.vcf | grep
DONOR_DISRUPTING

seems to be nothing?

but there are some Low Confidence LoF variants that fail some of the
LoF_filter:

cat LoF_cache_v89_VEP_output_for_dset_NE_chr_2.vcf | grep NON_CAN_SPLICE |
more
...

2       16805288        2:16805288      C       T       999     PASS
CSQ=T|upstream_gene_variant|MODIFIER|FAM49A|ENSG00000197872|Transcript|ENST00000355549|pro
tein_coding|||||||||||944|-1||HGNC|25373|||||,T|splice_acceptor_variant|HIGH|FAM49A|ENSG00000197872|Transcript|ENST00000381323|protein_coding||1/11||||||||||-1||H
GNC|25373||LC|NON_CAN_SPLICE&3UTR_SPLICE&ANC_ALLELE||INTRON_SIZE:41760,T|splice_acceptor_variant|HIGH|FAM49A|ENSG00000197872|Transcript|ENST00000406434|protein_co
ding||1/12||||||||||-1||HGNC|25373||LC|NON_CAN_SPLICE&3UTR_SPLICE&ANC_ALLELE||INTRON_SIZE:41760,T|splice_acceptor_variant|HIGH|FAM49A|ENSG00000197872|Transcript|E
NST00000445605|protein_coding||1/4||||||||||-1|cds_end_NF|HGNC|25373||LC|NON_CAN_SPLICE&3UTR_SPLICE&ANC_ALLELE||INTRON_SIZE:41971,T|splice_acceptor_variant|HIGH|F
AM49A|ENSG00000197872|Transcript|ENST00000451689|protein_coding||2/5||||||||||-1|cds_end_NF|HGNC|25373||LC|NON_CAN_SPLICE&3UTR_SPLICE&ANC_ALLELE||INTRON_SIZE:1708
...

**Comment by birndle** [comment]
Hmm, can you uncomment the line `print "$seq\n”;` in the function mes_donor_cache in loftee_splice_utils.pl and then re-run your VEP command? This will make it so that any time the MES function for donor splice sites is invoked, the 9-mer input sequence to this function will printed to stdout. This will help me to understand what’s going wrong.

Also, for your reference, below is a link to the output I got from running the following command:

~/ensembl-vep/vep  --offline --assembly GRCh37 --force_overwrite --cache --dir_cache ~/.vep --no_stats --plugin LoF,human_ancestor_fa:human_ancestor.fa.gz,loftee_path:./ --cache_version 89 -i NE_chr_2.rsnum.vcf.gz -o v89_output_latest.txt

https://drive.google.com/file/d/1fNM94ppxXEn6nzcNxF5LJ9g6nYFNcIQf/view?usp=sharing

Sorry again for the trouble. Hopefully we can sort this out soon.

Dan

**Comment by yunusbb** [comment]
Hello again,

Thank your for your help with this! loftee worked this time, but I see some
important differences between our output files
I mean annotations from your run and mine.  Several variants are called LC
in my run while they are HC stop_gained in your output (See example lines
below).
The dataset is one that I sent you before: NE_chr_2.rsnum.vcf.gz

So here is what I did:
Since I could not find the line you mentioned, i.e. 'print.. '
I updated the loftee plugin from git.
Then I uncommented the line '`print "$seq\n”;`'
Run loftee following your example command


module load tabix-0.2.6
module load perl-5.22.0

./ensembl-vep/vep --offline --assembly GRCh37 --force_overwrite --cache \
--dir_cache /ebc_data/bayazit1/.vep --no_stats \
--plugin
LoF,human_ancestor_fa:${w_dir}/ensembl-vep/ANC_SEQ/human_ancestor.fa.gz,loftee_path:/ebc_data/bayazit1/.vep/Plugins/loftee
\
--cache_version 89 -i ${w_dir}/NE_chr_2.rsnum.vcf.gz \
-o
${w_dir}/VEP_OUT/FINAL_uncommented_LoF_cache_v89_VEP_output_for_dset_NE_chr_2.txt
\
--dir_plugins /ebc_data/bayazit1/.vep/Plugins/loftee


Smartmatch is experimental at /ebc_data/bayazit1/.vep/Plugins/loftee/
de_novo_donor.pl line 175.
Smartmatch is experimental at /ebc_data/bayazit1/.vep/Plugins/loftee/
de_novo_donor.pl line 214.
Smartmatch is experimental at /ebc_data/bayazit1/.vep/Plugins/loftee/
splice_site_scan.pl line 191.
Smartmatch is experimental at /ebc_data/bayazit1/.vep/Plugins/loftee/
splice_site_scan.pl line 194.
Smartmatch is experimental at /ebc_data/bayazit1/.vep/Plugins/loftee/
splice_site_scan.pl line 238.
Smartmatch is experimental at /ebc_data/bayazit1/.vep/Plugins/loftee/
splice_site_scan.pl line 241.


cat FINAL_uncommented_LoF_cache_v89_VEP_output_for_dset_NE_chr_2.txt | grep
stop_gained | awk '{print $1,$3,$4,$5,$6,$14}'
...

2:242029817 A ENSG00000122085 ENST00000449133 Transcript
IMPACT=HIGH;STRAND=-1;FLAGS=cds_start_NF;LoF=LC;LoF_filter=NON_CAN_SPLICE_SURR;LoF_flags=;LoF_info=
2:242029817 A ENSG00000122085 ENST00000495694 Transcript
IMPACT=HIGH;STRAND=-1;LoF=LC;LoF_filter=NON_CAN_SPLICE_SURR;LoF_flags=;LoF_info=
2:242142814 T ENSG00000146205 ENST00000274979 Transcript
IMPACT=HIGH;STRAND=1;LoF=LC;LoF_filter=NON_CAN_SPLICE_SURR,ANC_ALLELE;LoF_flags=;LoF_info=
2:242142814 T ENSG00000146205 ENST00000402430 Transcript
IMPACT=HIGH;STRAND=1;LoF=LC;LoF_filter=NON_CAN_SPLICE_SURR,ANC_ALLELE;LoF_flags=;LoF_info=
2:242148997 T ENSG00000146205 ENST00000274979 Transcript
IMPACT=HIGH;STRAND=1;LoF=LC;LoF_filter=NON_CAN_SPLICE_SURR,ANC_ALLELE;LoF_flags=;LoF_info=
2:242148997 T ENSG00000146205 ENST00000402430 Transcript
IMPACT=HIGH;STRAND=1;LoF=LC;LoF_filter=NON_CAN_SPLICE_SURR,ANC_ALLELE;LoF_flags=;LoF_info=
2:242157261 A ENSG00000146205 ENST00000274979 Transcript
IMPACT=HIGH;STRAND=1;LoF=LC;LoF_filter=NON_CAN_SPLICE_SURR;LoF_flags=;LoF_info=
2:242157261 A ENSG00000146205 ENST00000402430 Transcript
IMPACT=HIGH;STRAND=1;LoF=LC;LoF_filter=NON_CAN_SPLICE_SURR;LoF_flags=;LoF_info=
2:242157261 A ENSG00000146205 ENST00000451047 Transcript
IMPACT=HIGH;STRAND=1;FLAGS=cds_start_NF,cds_end_NF;LoF=LC;LoF_filter=NON_CAN_SPLICE_SURR;LoF_flags=;LoF_info=
2:242688366 T ENSG00000180902 ENST00000537090 Transcript
IMPACT=HIGH;STRAND=1;LoF=LC;LoF_filter=END_TRUNC,NON_CAN_SPLICE_SURR,ANC_ALLELE;LoF_flags=;LoF_info=
2:242742843 G ENSG00000154252 ENST00000192314 Transcript
IMPACT=HIGH;STRAND=1;LoF=LC;LoF_filter=NON_CAN_SPLICE_SURR;LoF_flags=;LoF_info=

AND here are the last 19 output lines from your run:

zcat v89_output_latest.txt.gz | grep stop_gained | awk '{print
$1,$3,$4,$5,$6,$14}'
...
2:241903911 T ENSG00000226321 ENST00000442811 Transcript
IMPACT=HIGH;STRAND=1;FLAGS=cds_start_NF,cds_end_NF;LoF=HC;LoF_filter=;LoF_flags=;LoF_info=
2:242004778 A ENSG00000162804 ENST00000310397 Transcript
IMPACT=HIGH;STRAND=1;LoF=HC;LoF_filter=;LoF_flags=;LoF_info=
2:242004778 A ENSG00000162804 ENST00000342631 Transcript
IMPACT=HIGH;STRAND=1;LoF=HC;LoF_filter=;LoF_flags=;LoF_info=
2:242004778 A ENSG00000162804 ENST00000401884 Transcript
IMPACT=HIGH;STRAND=1;LoF=HC;LoF_filter=;LoF_flags=;LoF_info=
2:242004778 A ENSG00000162804 ENST00000405547 Transcript
IMPACT=HIGH;STRAND=1;LoF=HC;LoF_filter=;LoF_flags=;LoF_info=
2:242029817 A ENSG00000122085 ENST00000449133 Transcript
IMPACT=HIGH;STRAND=-1;FLAGS=cds_start_NF;LoF=HC;LoF_filter=;LoF_flags=;LoF_info=
2:242029817 A ENSG00000122085 ENST00000495694 Transcript
IMPACT=HIGH;STRAND=-1;LoF=HC;LoF_filter=;LoF_flags=;LoF_info=
2:242142814 T ENSG00000146205 ENST00000274979 Transcript
IMPACT=HIGH;STRAND=1;LoF=HC;LoF_filter=;LoF_flags=;LoF_info=
2:242142814 T ENSG00000146205 ENST00000402430 Transcript
IMPACT=HIGH;STRAND=1;LoF=HC;LoF_filter=;LoF_flags=;LoF_info=
2:242148997 T ENSG00000146205 ENST00000274979 Transcript
IMPACT=HIGH;STRAND=1;LoF=HC;LoF_filter=;LoF_flags=;LoF_info=
2:242148997 T ENSG00000146205 ENST00000402430 Transcript
IMPACT=HIGH;STRAND=1;LoF=HC;LoF_filter=;LoF_flags=;LoF_info=
2:242157261 A ENSG00000146205 ENST00000274979 Transcript
IMPACT=HIGH;STRAND=1;LoF=HC;LoF_filter=;LoF_flags=;LoF_info=
2:242157261 A ENSG00000146205 ENST00000402430 Transcript
IMPACT=HIGH;STRAND=1;LoF=HC;LoF_filter=;LoF_flags=;LoF_info=
2:242157261 A ENSG00000146205 ENST00000451047 Transcript
IMPACT=HIGH;STRAND=1;FLAGS=cds_start_NF,cds_end_NF;LoF=HC;LoF_filter=;LoF_flags=;LoF_info=
2:242688366 T ENSG00000180902 ENST00000537090 Transcript
IMPACT=HIGH;STRAND=1;LoF=LC;LoF_filter=END_TRUNC,ANC_ALLELE;LoF_flags=;LoF_info=
2:242742843 G ENSG00000154252 ENST00000192314 Transcript
IMPACT=HIGH;STRAND=1;LoF=HC;LoF_filter=;LoF_flags=;LoF_info=

It is notable that a number of variants are called as 'LC' in my run and
'HC' in your run?

BTW, no warnings file was generated this time.

**Comment by birndle** [comment]
Hey -

Glad to hear you can actually run it at last.

So, weirdly, I get the same output as you when I use --cache_version 91. I'm not sure yet what's causing these discrepancies. I guess our cache files must be different(?) Sorry, I don't have any answers at the moment. I will try re-downloading the cache files and running again.

Dan

**Comment by konradjk** [comment]
So I'm not sure of the exact solution here, but I will say that we generally use VEP and cache version 85 for all of our annotations. As far as I know, newer caches for GRCh37 have minor differences (if any) and so I'm hesitant to dive any further, but instead recommend only using with 85 or earlier. We will be building a version for GRCh38 that I will ensure works with newer versions.
