### ISSUE TITLE
HC LoF that are missense

### ISSUE THREAD

**Issue by dtaliun** [konradjk/loftee#29]
New version of loftee identifies some variants with missense_variant consequence as LoF HC.
I didn't notice this for previous loftee versions and its not documented.
Is it something that i should worry about or its a new loftee feature?
Thanks!

**Comment by konradjk** [comment]
Which version are you running, and can you give an example with the whole annotation you see (including LoF_flags)? The newer versions have some splice prediction tools, but I thought they would still be too buggy to use

**Comment by dtaliun** [comment]
I am trying to use it from VEP v91. I also need to mention that I am running it on GRCh38 with human_ancestor_fa:false,conservation_file:false. Will be not surprised that this is the reason....

chr22:15690183-A-G
`CSQ=G|missense_variant|MODERATE|POTEH|ENSG00000198062|Transcript|ENST00000343518|protein_coding|1/11||||158|106|36|R/G|Agg/Ggg||1||1||HGNC|HGNC:133|YES|CCDS74808.1|ENSP00000340610|Q6S545||UPI0000E5A425|deleterious_low_confidence(0.05)|benign(0)||||||||||||,G|upstream_gene_variant|MODIFIER|POTEH|ENSG00000198062|Transcript|ENST00000452800|nonsense_mediated_decay|||||||||||1|63|1|cds_start_NF|HGNC|HGNC:133|||ENSP00000442107||H0YG78|UPI000204A808||||||||||||||,G|missense_variant|MODERATE|POTEH|ENSG00000198062|Transcript|ENST00000621704|protein_coding|1/12||||106|106|36|R/G|Agg/Ggg||1||1||HGNC|HGNC:133|||ENSP00000477748||A0A087WTB9|UPI00015DF78F|deleterious_low_confidence(0.03)|benign(0.146)|||||||||HC|||DE_NOVO_DONOR&INTRON_START:15690315&INTRON_END:15690425&DE_NOVO_DONOR_MES_POS:-136&DE_NOVO_DONOR_PROB:0.995189872736245&EXON_END:15690314&EXON_START:15690078&DE_NOVO_DONOR_MES:6.48469757839982&MUTANT_DONOR_MES:1.66249485014675&DE_NOVO_DONOR_POS:-136,G|regulatory_region_variant|MODIFIER|||RegulatoryFeature|ENSR00000300933|CTCF_binding_site|||||||||||1|||||||||||||||||||||||||`

**Comment by konradjk** [comment]
Aha, yes, it's getting the new `DE_NOVO_DONOR` annotation, which means despite being a missense variant, it may also be predicted to disrupt splicing (creating a new donor site). I must warn that these new annotations are experimental and should be used with caution.
