### ISSUE TITLE
 MSG: Slice start cannot be greater than slice end

### ISSUE THREAD

**Issue by zhouhufeng** [konradjk/loftee#34]

**Comment by konradjk** [comment]
Hello!

If you're still having this issue, please provide an example SNP where this occurs and some more output from the warning.

Thanks!
-Konrad

**Comment by yangyxt** [comment]
Hi I'm still having this issue on GRCh37 on vep version 104. Input format is VCF
The error message does not provide specific variants where the errors are hit. I checked the entire vcf and make sure no END coordinates recorded in INFO field is smaller than the POS value.
