### ISSUE TITLE
hg38 files

### ISSUE THREAD

**Issue by zhouhufeng** [konradjk/loftee#38]
We have step up the VEP and LOFTEE successfully, and the current final question is, can we run Loftee Plugin for hg38?

I found the files in your FTP is required for us to run loftee,
https://personal.broadinstitute.org/konradk/loftee_data/GRCh37/

[   ]	GERP_scores.final.sorted.txt.gz	11-Jan-2018 11:05 	11G	 
[   ]	GERP_scores.final.sorted.txt.gz.tbi	11-Jan-2018 12:39 	2.8M	 
[   ]	human_ancestor.fa.gz	13-Mar-2015 16:31 	834M	 
[   ]	human_ancestor.fa.gz.fai	13-Mar-2015 16:32 	736 	 
[   ]	human_ancestor.fa.gz.gzi	13-Mar-2015 16:32 	748K	 
[   ]	phylocsf_gerp.sql	15-Jan-2018 20:25 	416M	 

 

And for hg38, I found found the file:
https://personal.broadinstitute.org/konradk/loftee_data/GRCh38/
[   ]	human_ancestor.fa.gz	11-Sep-2018 09:46 	844M	 
[   ]	human_ancestor.fa.gz.fai	11-Sep-2018 09:49 	736 	 
[   ]	human_ancestor.fa.gz.gzi	11-Sep-2018 09:49 	747K	 

I seems that we still don't have phylocsf_gerp.sql for hg38(CRGh38), I am wondering if it is possible for us to have phylocsf_gerp.sql in hg38 so that we can quickly run loftee on our large variant dataset?

**Comment by Hoeze** [comment]
I'm running into the same issue.
How would I run LOFTEE with VEP on hg38?

**Comment by Quio-Enrique** [comment]
Hey!
I recently checked the updates and the new files are supposed to be there:
https://github.com/konradjk/loftee/tree/grch38

However, when I tried to download them, I just keep getting the message that I do not have permissions to access it (Forbidden).

Has anyone managed to download the GRCh38 files?

Thanks!

**Comment by spatel-gfb** [comment]
@Quio-Enrique : Loftee isn't compatible to run with hg38 yet. We tried using it earlier but it didn't work. I see the files are now not present in the path provided and its empty. We have the sql.gz file which it used before in S3 , so if you would like to have that sql.gz (GRCh37) file, I can make it available temporarily through some means.

But the long term solution would be to fix the path by contacting the maintainer.

**Comment by Quio-Enrique** [comment]
Hi @spatel-gfb ,

Thank you very much for your reply and your kind offer.
I also have the GRCh37 files, thanks a lot.
Would you then recommend to lift the VCF to GRCh37 and run everything with that assembly?

Thanks again for your answer!

**Comment by spatel-gfb** [comment]
@Quio-Enrique : The fastest way to go will be that only, coz hg38 is not yet working or tested.

**Comment by Quio-Enrique** [comment]
Hi @konradjk,

Thank you very much for your reply.
Links are working now :)

**Comment by andrimar1** [comment]
> Hi @konradjk,
> 
> Thank you very much for your reply. Links are working now :)

@Quio-Enrique  did you manage to Loftee working for hg38 after you got the data ?

**Comment by Quio-Enrique** [comment]
@andrimar1 only up to certain point and it worked fine, but I stopped trying as I got what I was looking for.
But I am sure with the new files it can work fine.
