### ISSUE TITLE
Failed to compile plugin LoF

### ISSUE THREAD

**Issue by edicks** [konradjk/loftee#41]
Hello, I installed vep v94, installed the maxEntScan plugin and loftee plugin via;
wget https://github.com/konradjk/loftee/archive/master.zip
set the PERL5LIB env to be the loftee location (same as vep plugin directory)
Ran vep/loftee cmd;
/usr/local/exports/bin/emd43/ensembl-vep/vep -i ~/ngs/54gene_unique_vars.vcf -o ~/ngs/54gene_unique_vars_out.vcf --fasta ~/ngshome/human_ref_hg19_chr.fa --cache --offline --dir_plugins /usr/local/exports/bin/emd43/ensembl-vep/.vep/Plugins/ --dir_cache /usr/local/exports/bin/emd43/ensembl-vep/.vep --dir /usr/local/exports/bin/emd43/ensembl-vep/.vep --assembly GRCh37 --force_overwrite --exclude_predicted --no_stats --ccds --canonical --refseq --vcf --plugin MaxEntScan,/usr/local/exports/bin/emd43/ensembl-vep/.vep/Plugins/maxEntScan --plugin LoF,loftee_path:/usr/local/exports/bin/emd43/ensembl-vep/.vep/Plugins

the vep runs ok and annotates variants with maxEntScan scores, but loftee does not run as it
fails to compile;
WARNING: Failed to compile plugin LoF: Can't open me2x3acc1!
Compilation failed in require at /usr/local/exports/bin/emd43/ensembl-vep/.vep/Plugins/loftee_splice_utils.pl line 4.
Compilation failed in require at /usr/local/exports/bin/emd43/ensembl-vep/.vep/Plugins/LoF.pm line 33.

This looks very similar to issue #19 which was resolved at the time. I tried running the same cmd in
the loftee directory and see a different error;
WARNING: Failed to compile plugin LoF: can't open!

but;
gen01(90) ll LoF.pm
-rw-r--r-- 1 ed ed 23363 Aug 29 14:35 LoF.pm
gen01(91) echo $PERL5LIB
.:/usr/local/exports/bin/emd43/ensembl-vep/.vep/Plugins

Can anyone help on this?
Thanks, Ed

**Comment by konradjk** [comment]
We've recently updated LOFTEE to require additional files to be on your path. I've updated the README a bit, but if you move not just LoF.pm but all the files from the repo into `.../.vep/Plugins` that should fix the problem.

**Comment by edicks** [comment]
Ok Thanks
