### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by hartleys** [konradjk/loftee#43]
Based on the posted issues from the past, it looks like you used to have some of the required annotation files here:

https://personal.broadinstitute.org/konradk/loftee_data/GRCh37/

But that folder is now empty. Could you return the gerp and similar annotation files? As far as I can tell it's not possible to get useful results out of loftee without them (the loftee fields are just blank).

**Comment by konradjk** [comment]
Ah yes, apologies. We migrated file systems and looks like some permissions did not get updated. I've put in a request to reinstate these.

**Comment by konradjk** [comment]
Ok these should be fixed now. Let me know if you have trouble accessing any of the files now
