### ISSUE TITLE
Is LOFTEE thread safe?

### ISSUE THREAD

**Issue by koelling** [konradjk/loftee#45]
Can I run vep with the `--fork` flag while using LOFTEE? I tried to run it with `--fork 8` and it seemed to run into occasional problems with the SQLite databases based on these error messages:

```
DBD::SQLite::st execute failed: database disk image is malformed at vep/plugins/LoF.pm line 565.
WARNING: Plugin 'LoF' went wrong: MySQL ERROR: No such file or directory at vep/plugins/LoF.pm line 565.
Use of uninitialized value $number_of_exons in subtraction (-) at vep/plugins/LoF.pm line 586, <__ANONIO__> line 60180.
Use of uninitialized value in split at vep/plugins/LoF.pm line 573, <__ANONIO__> line 60180.
```

When I remove the `--fork` parameter I don't get any such errors.

**Comment by konradjk** [comment]
I've definitely had issues with this before, so I stopped using `--fork` and instead opting to parallelize by chunks of variants (I would typically find that VEP handles memory better if you do that anyway).
