### ISSUE TITLE
Interpreting output

### ISSUE THREAD

**Issue by gregmcinnes** [konradjk/loftee#46]
I have a pretty simple question.  I'm trying to understand what the output means after running VEP with loftee.  I see some variants with the annotation: LoF=HC;LoF_info=....   Which I understand is a high confidence loss of function variant.  However there are other sites that only have LoF_info flags and no other LoF annotations (no LoF=HC, nor LoF=LC).  Does that mean that the site is not a loss of function site?

Thanks

**Comment by konradjk** [comment]
Correct. We recently added some splice annotations (which should get an OS designation if they pass), which add some data into LoF_info for logging purposes. Probably should have cleaned that up, but it is what it is (and maybe someone will find it useful).
