### ISSUE TITLE
Run VEP + LOFTEE with GRCh38:    no such table: gerp_exons

### ISSUE THREAD

**Issue by yongsheng268** [konradjk/loftee#51]
hello there!     

Need your help as I am fighting this strange error.     Here is the situation 
1)  VEP definitely works as expected
2) LOFTEE appears to be installed correctly
3) Data required by LOFTEE are verified to be in correct paths.   
4) Particularly,  GRCh38 version PhyloCSF databases (loftee.sql) is downloaded (as instructed) from.  https://personal.broadinstitute.org/konradk/loftee_data/GRCh38/
5) However,  keep running into this issue of "no such table: gerp_exons".   My understanding is that the "gerp_exons" will only be needed for GRCh37 (not GRCh38).     I loaded the "loftee.sql" into sqlite3.  There is only one table "phylocsf_summary".       

Please can someone (especially Konrad) kindly shed some lights on what might be the root cause?    Many thanks!

========================================
This is my command line

%sh
export PERL5LIB=$PERL5LIB:/statgen/variant_annotation/data/.vep/Plugins:/statgen/variant_annotation/data/.vep/Plugins/loftee
/statgen/variant_annotation/vep/ensembl-vep/vep \
--assembly GRCh38 \
--dir /statgen/variant_annotation/data/.vep/ \
--cache \
--dir_cache /statgen/variant_annotation/data/.vep \
--offline \
--merged \
--force_overwrite \
--everything \
--dir_plugins /statgen/variant_annotation/data/.vep/Plugins/loftee/ \
--plugin LoF,loftee_path:/statgen/variant_annotation/data/.vep/Plugins/loftee/,human_ancestor_fa:/statgen/variant_annotation/data/human_ancestor.fa.gz,conservation_file:/statgen/variant_annotation/data/loftee.sql,gerp_bigwig:/statgen/variant_annotation/data/gerp_conservation_scores.homo_sapiens.GRCh38.bw \
--vcf \
-i /dbfs/users/jliu5/test_ukbb_data.vcf.bgz \
-o /tmp/test_ukbb_data_vep_annotated.vcf

========================================
Below is the error stack trace:

Use of uninitialized value in pattern match (m//) at /statgen/variant_annotation/data/.vep/Plugins/loftee/LoF.pm line 137.

2019-05-17 22:49:24 - INFO: BAM-edited cache detected, enabling --use_transcript_ref; use --use_given_ref to override this

WARNING: Plugin 'LoF' went wrong: Can't call method "execute" on an undefined value at /statgen/variant_annotation/data/.vep/Plugins/loftee/gerp_dist.pl line 130, <$fh> line 4455.

DBD::SQLite::db prepare failed: no such table: gerp_exons at /statgen/variant_annotation/data/.vep/Plugins/loftee/gerp_dist.pl line 129, <$fh> line 4455.
DBD::SQLite::db prepare failed: no such table: gerp_exons at /statgen/variant_annotation/data/.vep/Plugins/loftee/gerp_dist.pl line 129, <$fh> line 4455.
DBD::SQLite::db prepare failed: no such table: gerp_exons at /statgen/variant_annotation/data/.vep/Plugins/loftee/gerp_dist.pl line 129, <$fh> line 4455.
DBD::SQLite::db prepare failed: no such table: gerp_exons at /statgen/variant_annotation/data/.vep/Plugins/loftee/gerp_dist.pl line 129, <$fh> line 4455.
DBD::SQLite::db prepare failed: no such table: gerp_exons at

< ... the above error message repeats many times ...>

**Comment by konradjk** [comment]
Are you using the grch38 branch? Make sure that one is checked out in the directory you’ve pointed VEP to

**Comment by yongsheng268** [comment]
Thanks Konrad!   I definitely checked out the GRCh38 branch of LOFTEE which is installed in .vep/Plugins.   

I can try to copy it to VEP binary path and see how it goes.  Thanks

**Comment by yongsheng268** [comment]
Konrad,  I did install the GRCh38 branch (see below).    is there a way that I can confirm that LOFTEE is calling the right GRCh38 at runtime ? 

git clone --single-branch --branch grch38 https://github.com/konradjk/loftee.git

**Comment by yongsheng268** [comment]
It turned out that my LOFTEE was not correctly installed the GRCh38 version.     However, after fix that issue with pulling down the right grch38 branch,  run into another issue of Bio::DB::BigWig install.   I tried to follow the example on UCSC but end up with not being able to link Kent's own htslib.a.   See details at https://github.com/GMOD/GBrowse-Adaptors/issues/17

In the end, I was able to completely resolve the issue by following VEP's installation instruction (Bio::DB::BigFile)
https://useast.ensembl.org/info/docs/tools/vep/script/vep_download.html#bigfile
Note that it pulls down an older version of BigFile/BigWig (v335_base.tar.gz).    It worked out perfectly. 


I am going to close the this issue ticket.   However,  in the GRCh38 LOFTEE install guide, I'd recommend that you add dependencies of BigWig and point users to VEP install guide.   Going through the other route (direct pull from UCSC) could be long and winding road.  


To be of help,  all VEP (plugins, dependencies) and LOFTEE, BigFile are installed and tested on EC2 / Ubuntu (x86_64)

**Comment by Mingxi-HUANG-Sunnia** [comment]
Hi, I also got this error! I solve this by these steps:

1.install the GRCh38 branch loftee
git clone --single-branch --branch grch38 https://github.com/konradjk/loftee.git

2.also run into the issue of Bio::DB::BigWig install, I use conda to install it
https://bioconda.github.io/recipes/perl-bio-bigfile/README.html?highlight=bigfile
conda install perl-bio-bigfile

then， works done！
