### ISSUE TITLE
LOFTEE cannot annotate GRCh37 variants by using latest GENCODE

### ISSUE THREAD

**Issue by koido** [konradjk/loftee#54]
Hi,

I'm using LOFTEE to annotate variants mapped to GRCh37.
I noticed that VEP caches for GRCh37 were only available for gene and transcript ids in old GENCODE release 19. (https://m.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache)

I tried to set latest GENCODE (e.g., release 29) gff files by --gff argument; but LOFTEE saw GENCODE release 19 in vep cache.
In fact, "ENSG00000069712" does not exist in GENCODE release 29 but was included in the output file.
In offline vep, I cannot run LOFTEE without setting the vep cache.
How can I annotate GRCh37 variants using the specified, latest GENCODE?

Although what I need would be to update vep cache by using my latest GENCODE release, how can I make the vep cache for LOFTEE?

I'm using vep 96.0 or 97.0.
Thanks a lot.

Best,
Masaru

**Comment by konradjk** [comment]
We have not yet successfully run a newer version of Gencode (>19) on GRCh37 using VEP let alone LOFTEE. Unfortunately we don't really have the bandwidth to patch this, as the community is moving to GRCh38 and there new Gencode versions are supported natively (we have tested up to VEP v95 using GRCh38). If you want to use GRCh37, unfortunately the only mechanism we can support at this time is VEP <= v85 with Gencode v19.
