### ISSUE TITLE
How did gnomAD team process their variants with LOFTEE?

### ISSUE THREAD

**Issue by seunghun23** [konradjk/loftee#71]
Hi, 

I was trying to use LOFTEE as a vep-plugin and I learned from this forum that it can't be really run with vep's "fork" option for parallelization (https://github.com/konradjk/loftee/issues/61). Since I need to run VEP with many plugins on large cohorts, turning off the fork option isn't an option for me here, and I was wondering how gnomAD team actually used LOFTEE without parallelization when there must have been huge amount of variants to process. (or is there a way to run VEP and LOFTEE with --fork option? looks like the thread above never got an answer)

Best,
Seunghun

**Comment by konradjk** [comment]
Hello! For the last several years, we have been using [Hail](https://hail.is/index.html) to run VEP on our large datasets. Prior to that, we manually partitioned the genome into ~1000-5000 chunks of ~10000-20000 variants each and dispatched the tasks on a UGER system.

**Comment by seunghun23** [comment]
I see... thank you for your response!
