### ISSUE TITLE
Different LoF confidence when adding --fasta option

### ISSUE THREAD

**Issue by koido** [konradjk/loftee#76]
Thank you for providing a very nice tool.
I'm using the LOFTEE GRCh38 plugin with the VEP v100 in offline mode.

I found that adding --fasta option in VEP changes several HC pLoF variants into LC pLoF with GC_TO_GT_DONOR flag.
Because your README file does not describe the importance of the --fasta option, I want to confirm which is the expected behavior.

I attached my commands and input/output files as examples.
[examples.tar.gz](https://github.com/konradjk/loftee/files/6070137/examples.tar.gz)

Best regards,
Masaru

**Comment by konradjk** [comment]
Hello!

Definitely adding `--fasta` will make it more accurate as it then has more information about the reference genome in order to make these calls.

Best,
-Konrad
