### ISSUE TITLE
Need to mention in README that master branch has issues with GRCh38

### ISSUE THREAD

**Issue by davmlaw** [konradjk/loftee#88]
GRCh38 is the most current human reference genome, and is likely seen as the default in 2022

There is no mention in the initial README about using GRCh38 branch, this information is found buried in the issues

**Comment by sahwa** [comment]
@davmlaw  Do you know if the grch38 branch is still recommended? Hasn't been updated in 3 years, so unsure if it's better to use the master branch?

**Comment by davmlaw** [comment]
I assume so, there have been no commits since my issue has been raised.

I gave up as I need my pipeline to run both GRCh37 and GRCh38 and it was a pain to get working. Instead I use LoF plugins from [dbNSFP](https://sites.google.com/site/jpopgen/dbNSFP?pli=1)
