### ISSUE TITLE
SQL Database not accessible

### ISSUE THREAD

**Issue by bethrusnak** [konradjk/loftee#89]
Location of file with PhyloCSF metrics (make sure these are unzipped locally before use!):

GRCh38:

The required SQL database (gzipped) can be downloaded [here](https://personal.broadinstitute.org/konradk/loftee_data/GRCh38/loftee.sql.gz).

The link give:
Forbidden
You don't have permission to access /konradk/loftee_data/GRCh38/loftee.sql.gz on this server.

**Comment by konradjk** [comment]
Apologies - the files got moved, but they should now be back up.
